--- 
abstract: View information about an NES game from a ROM file
author: Brian Cassidy <bricas@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Games-NES-ROM
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Digest::CRC: 0
  Test::More: 0
version: 0.05
