---
name: Games-NES-ROM
version: 0.04
author:
  - 'Brian Cassidy <bricas@cpan.org>'
abstract: View information about an NES game from a ROM file
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0
  Digest::CRC: 0
build_requires:
  Test::More: 0
provides:
  Games::NES::ROM:
    file: lib/Games/NES/ROM.pm
    version: 0.04
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
